runs:
  using: 'composite'
  steps:
    - name: ğŸ¥¸ Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        version: 9
        run_install: false

    - name: ğŸ¤ Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 18

    - name: âš™ï¸ Install dependencies
      run: pnpm install
      shell: bash
